import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const faqs = [
  {
    question: "What is semantic search?",
    answer:
      "Semantic search understands the meaning behind your query, not just the exact words. For example, if you search for 'data privacy,' it will find bills about 'information security,' 'consumer data protection,' and 'personal information safeguards' even if those exact phrases don't appear in the bill text. This is different from keyword search, which only finds exact word matches. Semantic search uses AI to understand context and intent, making it much more powerful for finding relevant legislation.",
  },
  {
    question: "How accurate are AI summaries?",
    answer:
      "Our AI summaries are highly accurate and include citations to specific bill sections so you can verify any claim. The summaries are generated by advanced language models trained on legislative text, and they focus on extracting factual information: key provisions, affected stakeholders, estimated impact, and procedural status. However, we always recommend reviewing the original bill text for critical decisions, which is why we include source citations in every summary.",
  },
  {
    question: "Which jurisdictions do you cover?",
    answer:
      "We currently cover federal legislation and are expanding to all 50 states. Our initial focus is on high-volume jurisdictions where we can provide the most value. If you need coverage for a specific state, please contact us—we're prioritizing based on customer demand. We also track regulatory changes from major federal agencies.",
  },
  {
    question: "How does this compare to [Competitor]?",
    answer:
      "Unlike legacy platforms built in the 1990s, Legislative Intake is built from the ground up with modern AI capabilities. We offer real-time alerts (sub-minute latency vs. hours), semantic search (not just keywords), and automatic bill classification. Our pricing is transparent and doesn't charge per user, making it more cost-effective for teams. Most importantly, we focus on use before value—you can try the platform free before committing to a paid plan.",
  },
  {
    question: "Can I try it before committing?",
    answer:
      "Absolutely! We offer a free trial with no credit card required. You can upload bills, test the AI summaries, try semantic search, and explore all features. We want you to experience the value before making any commitment. Setup takes just minutes.",
  },
  {
    question: "What data sources do you use?",
    answer:
      "We pull data directly from official legislative sources: state legislative websites, Congress.gov, and regulatory agency feeds. We use real-time APIs where available and automated monitoring for jurisdictions that don't offer APIs. All data is sourced from official government sources to ensure accuracy and timeliness.",
  },
  {
    question: "Is my data secure?",
    answer:
      "Yes, security is a top priority. We use industry-standard encryption for data in transit and at rest. Your uploaded documents and bill tracking data are private to your organization. We comply with SOC 2 Type II standards and regularly undergo security audits. We never share your data with third parties or use it for training AI models without your explicit consent.",
  },
  {
    question: "Can I export my data?",
    answer:
      "Yes, you can export all your data at any time. We provide exports in multiple formats (CSV, JSON, PDF) so you can integrate with your existing systems or maintain backups. Your data belongs to you, and we make it easy to take it with you if you ever decide to switch platforms.",
  },
  {
    question: "How fast are the alerts?",
    answer:
      "We provide sub-minute alerts for bills matching your criteria. As soon as a bill is introduced, amended, or changes status on the official legislative website, our system processes it and sends you an alert. This is significantly faster than legacy platforms, which often have delays of hours or even days.",
  },
  {
    question: "Do you offer API access?",
    answer:
      "Yes, we offer API access for enterprise customers who want to integrate Legislative Intake with their existing systems. Our API provides programmatic access to bill data, summaries, search functionality, and alerts. Contact us to discuss your integration needs and API pricing.",
  },
]

export function FAQ() {
  return (
    <section id="faq" className="container py-24">
      <div className="mb-12 text-center">
        <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
          Frequently Asked Questions
        </h2>
        <p className="mt-4 text-lg text-muted-foreground">
          Everything you need to know about Legislative Intake
        </p>
      </div>

      <div className="max-w-3xl mx-auto">
        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, index) => (
            <AccordionItem key={index} value={`item-${index}`}>
              <AccordionTrigger className="text-left">
                {faq.question}
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  )
}

